#######################################################################
#   Copyright [2014] [Cisco Systems, Inc.]
# 
#   Licensed under the Apache License, Version 2.0 (the \"License\");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
# 
#       http://www.apache.org/licenses/LICENSE-2.0
# 
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an \"AS IS\" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#######################################################################

include $(CCSP_ROOT_DIR)/arch/ccsp_common.mk

source_files := $(call add_files_from_src,,'*.c')
source_files += $(call add_files_from_board,,'*.c')
obj_files := $(addprefix $(ComponentBuildDir)/, $(source_files:%.c=%.o))
-include $(obj_files:.o=.d)

INCPATH += $(ComponentSrcDir)

CFLAGS += $(addprefix -I, $(INCPATH))

target1 := $(ComponentBuildDir)/CcspLMLite

$(target1): $(obj_files)
	@echo "Creating Binary...[$(ComponentBaseDir)/$@]"
	@$(CC) $(LDFLAGS) -llmapi $^ -o $@ 2> $(@:%=%.warn) || (cat $(@:%=%.warn); exit 1)

target2 := $(ComponentBuildDir)/liblmapi.so
source_files2 := $(call add_files_from_src,,'lm_api.c')
obj_files2 := $(addprefix $(ComponentBuildDir)/, $(source_files2:%.c=%.o))
-include $(obj_files2:.o=.d)

$(target2): $(obj_files2)

targets := $(target2) $(target1)
	
all: $(targets)

clean:
	rm -rf $(ComponentBuildDir)

install: stage install_fs

install_fs:
	@-mkdir -p $(CCSP_OUT_DIR)/lm
	@cp $(targets) $(CCSP_OUT_DIR)/lm
	cp $(ComponentBuildDir)/liblmapi.so ${CCSP_INSTALL_ROOT}/lib

stage:
	@cp $(ComponentSrcDir)/lm_api.h ${CCSP_STAGING_ROOT}/include
	@cp $(ComponentBuildDir)/liblmapi.so ${CCSP_STAGING_ROOT}/lib

.PHONY: all clean install install_fs stage

LDFLAGS += -lccsp_common
LDFLAGS += -L$(ComponentBuildDir)
